# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: DevSkim

on:
  push:
    branches: 
      - master
      - renovate/**
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '23 8 * * 2'

permissions:
  contents: read

jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f70248679df316796ffb7123cb0b916bd98cde22
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout code
        uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@7ac186de008d6d0b77a8aef3f15dacd6b612ac17
        
      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@6cfb483131f3f74950a251876da81c79a6fcbdec
        with:
          sarif_file: devskim-results.sarif
