# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: DevSkim

on:
  push:
    branches: 
      - master
      - renovate/**
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '23 8 * * 2'

permissions:
  contents: read

jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@394d78e5b40cc35c170eb909b1f81551f37feb05
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@6dc2931366b1d31380324c6bfff84b3a8fd10401
        
      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@07d42ec34e55d7e17f411bffdf54e254effd68ae
        with:
          sarif_file: devskim-results.sarif
