# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: DevSkim

on:
  push:
    branches: 
      - master
      - renovate/**
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '23 8 * * 2'

permissions:
  contents: read

jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@39fa126de8af73ab0d455b56764f8fe42b5e6a91
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout code
        uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@7ac186de008d6d0b77a8aef3f15dacd6b612ac17
        
      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@130884e4e1961d7e595c85e8e60b206e0f5282e7
        with:
          sarif_file: devskim-results.sarif
