# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: DevSkim

on:
  push:
    branches: 
      - master
      - renovate/**
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '23 8 * * 2'

permissions:
  contents: read

jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18f6947f131da60743dc12d2a22ff28c2b4ea87f
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@914fa647b406c387000300b2f09bb28691be2b6d
        
      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@7ae5fc37a2d86720045717aa7fa9ea16514bde6f
        with:
          sarif_file: devskim-results.sarif
