name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@394d78e5b40cc35c170eb909b1f81551f37feb05
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@72f2cec99f417b1a1c5e2e88945068983b7965f9
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@32c3156f63f31a54dece4ce3e32dbb767c38bb61
        with:
          linter: jetbrains/qodana-python
