name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ea8b747819ff6d82907eb4018229f1a75c174697
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@7cf87a03ac7ee50ab738d24489ff703a66c74371
        with:
          linter: jetbrains/qodana-python
