name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3b1c91e8873ae0c705b0709f957c7a6a5eaf10
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@aadec899646c8e0f34c52d9219c2faac36626b55
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@9a71424636be05dccc139d34e7248de96fd15d9c
        with:
          linter: jetbrains/qodana-python
