name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9ff9d14760a73102d9fa2f47131624137f50ead8
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@48916dfaa9f44af0fd4433a5af7faf0cb86e4f7d
        with:
          linter: jetbrains/qodana-python
