name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a22641e386edd6104ead99416bac876f4d9b806d
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@6572bc67384e2f641d4926af96379266ae166a6e
        with:
          linter: jetbrains/qodana-python
