name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3b1c91e8873ae0c705b0709f957c7a6a5eaf10
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@c0a36fb50f89f631c068153f5cf03964ba32861f
        with:
          linter: jetbrains/qodana-python
