name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4f3f445f343c08c93d7771433e8dee4267e05b9
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@b80ff79f1755d06ba70441c368a6fe801f5f3a62
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@694e2ff7671102486087f970864dd3c7a3eb97db
        with:
          linter: jetbrains/qodana-python
