name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b4401455ef773683d2da2e176e3539cce0fabdc7
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@bf085276cecdb0cc76fbbe0687a5a0e786646936
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@02cc364ad985bd673e0758e6218890bd1bd27959
        with:
          linter: jetbrains/qodana-python
