name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e680f76da57a1e1ce6dc3eed69efc703fcca8dce
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@ab695492d98902c49b33382782175107ec63ca28
        with:
          linter: jetbrains/qodana-python
