name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@465ee407414b11a1069764835c1287d8de5ad0cc
        with:
          linter: jetbrains/qodana-python
