name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@56b75a26f8bd4688878746adecd21a273b119105
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@6a84743051be17cee477b0a26bd866b5dba996e4
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@f8a64bc18ee8f15e4a7c6e092270c470da7ad091
        with:
          linter: jetbrains/qodana-python
