name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@29e9ae12297382bde04e940b27e0638029f9f3cd
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@86eb286695b6eecb6e4120671ad9516cf4758407
        with:
          linter: jetbrains/qodana-python
