name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c0db65e1f64025718795419be8dbbf8c4050160f
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@8cd55970abf5011d45b17286c1dc06acf2ad1fe7
        with:
          linter: jetbrains/qodana-python
