name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@28278524d0a2e042c57b6713ad659f1b2c13c0ac
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@8230315d06ad95c617244d2f265d237a1682d445
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@985c550d4cdf83b1415aa22e09ac675ae26b49e1
        with:
          linter: jetbrains/qodana-python
