name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cbe522639944d3247f1f8832639650558051f9b7
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@27135e314dd1818f797af1db9dae03a9f045786b
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@7afb26c0c2f325c0d5c21ea1f617c79c7f899337
        with:
          linter: jetbrains/qodana-python
